add os.path.abspath() in dirname generation of the reloader
Otherwise adding a watcher for a file located in the working directory generates an empty dirname, resulting in the following error:
inotify.calls.InotifyError: Call failed (should not be -1): (-1) ERRNO=(0)

Caused by the fact that we call inotify with an empty path