Validate directory before watching it with inotify
Fixes this exception that is raised when the inotify-based reloader is used in
combination with the `--chdir` option:

    inotify.calls.InotifyError: Call failed (should not be -1): (-1) ERRNO=(0)